# Generated by Django 4.2.6 on 2024-05-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='getImage',
        ),
    ]
