# Generated by Django 4.2.6 on 2024-05-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0002_rename_image_getimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getimage',
            name='date',
        ),
        migrations.AddField(
            model_name='getimage',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='getimage',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
