# Generated by Django 4.2.6 on 2024-05-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0003_remove_getimage_date_getimage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getimage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
